In [4]:
import pandas as pd

In [6]:
import numpy as np

In [1]:
from sklearn.model_selection import cross_val_score

In [2]:
from sklearn.model_selection import LeaveOneOut, LeavePOut

In [3]:
loocv = LeaveOneOut()

In [22]:
num = np.arange(10, 20)

In [37]:
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
res = loocv.split(num)

In [44]:
res

<generator object BaseCrossValidator.split at 0x0000023B99CE1440>

In [45]:
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
var = list(res)

In [42]:
list(res)

[]

In [47]:
var

[(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0])),
 (array([0, 2, 3, 4, 5, 6, 7, 8, 9]), array([1])),
 (array([0, 1, 3, 4, 5, 6, 7, 8, 9]), array([2])),
 (array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([3])),
 (array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4])),
 (array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([5])),
 (array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([6])),
 (array([0, 1, 2, 3, 4, 5, 6, 8, 9]), array([7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 9]), array([8])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([9]))]

In [48]:
var

[(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0])),
 (array([0, 2, 3, 4, 5, 6, 7, 8, 9]), array([1])),
 (array([0, 1, 3, 4, 5, 6, 7, 8, 9]), array([2])),
 (array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([3])),
 (array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4])),
 (array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([5])),
 (array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([6])),
 (array([0, 1, 2, 3, 4, 5, 6, 8, 9]), array([7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 9]), array([8])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([9]))]

In [49]:
var

[(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0])),
 (array([0, 2, 3, 4, 5, 6, 7, 8, 9]), array([1])),
 (array([0, 1, 3, 4, 5, 6, 7, 8, 9]), array([2])),
 (array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([3])),
 (array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4])),
 (array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([5])),
 (array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([6])),
 (array([0, 1, 2, 3, 4, 5, 6, 8, 9]), array([7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 9]), array([8])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([9]))]

In [51]:
for i in res :
    print(i)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0]))
(array([0, 2, 3, 4, 5, 6, 7, 8, 9]), array([1]))
(array([0, 1, 3, 4, 5, 6, 7, 8, 9]), array([2]))
(array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([3]))
(array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4]))
(array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([5]))
(array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([6]))
(array([0, 1, 2, 3, 4, 5, 6, 8, 9]), array([7]))
(array([0, 1, 2, 3, 4, 5, 6, 7, 9]), array([8]))
(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([9]))


In [52]:
for i in res :
    print(i)

### Leave P Out

In [54]:
a = 100
print(a)

100


In [55]:
a = 200
print(a)

200


In [56]:
x = "Zebra"
print(x)
print(id(x))

Zebra
2455007007616


In [57]:
y = "Horse"
print(y)
print(id(y))

Horse
2455008800768


In [58]:
z = "Zebra"
print(z)
print(id(z))

Zebra
2455007007616


In [60]:
mstr = "zebra and horse look alike"

In [61]:
len(mstr)

26

In [62]:
mstr[1]

'e'

In [63]:
id(mstr[1])

140715935838368

In [64]:
mstr[14]

'e'

In [65]:
id(mstr[14])

140715935838368

In [79]:
from sklearn.model_selection import LeavePOut

In [80]:
lpocv = LeavePOut(p=2)

In [81]:
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [82]:
res1 = lpocv.split(num)

In [83]:
import time

In [84]:
for i in res1:
    print(i)
    print()
    time.sleep(0.5)

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1]))

(array([1, 3, 4, 5, 6, 7, 8, 9]), array([0, 2]))

(array([1, 2, 4, 5, 6, 7, 8, 9]), array([0, 3]))

(array([1, 2, 3, 5, 6, 7, 8, 9]), array([0, 4]))

(array([1, 2, 3, 4, 6, 7, 8, 9]), array([0, 5]))

(array([1, 2, 3, 4, 5, 7, 8, 9]), array([0, 6]))

(array([1, 2, 3, 4, 5, 6, 8, 9]), array([0, 7]))

(array([1, 2, 3, 4, 5, 6, 7, 9]), array([0, 8]))

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([0, 9]))

(array([0, 3, 4, 5, 6, 7, 8, 9]), array([1, 2]))

(array([0, 2, 4, 5, 6, 7, 8, 9]), array([1, 3]))

(array([0, 2, 3, 5, 6, 7, 8, 9]), array([1, 4]))

(array([0, 2, 3, 4, 6, 7, 8, 9]), array([1, 5]))

(array([0, 2, 3, 4, 5, 7, 8, 9]), array([1, 6]))

(array([0, 2, 3, 4, 5, 6, 8, 9]), array([1, 7]))

(array([0, 2, 3, 4, 5, 6, 7, 9]), array([1, 8]))

(array([0, 2, 3, 4, 5, 6, 7, 8]), array([1, 9]))

(array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3]))

(array([0, 1, 3, 5, 6, 7, 8, 9]), array([2, 4]))

(array([0, 1, 3, 4, 6, 7, 8, 9]), array([2, 5]))



In [86]:
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [85]:
lpocv3 = LeavePOut(p = 3)

In [89]:
res3 = lpocv3.split(num)

In [90]:
result = list(res3)

In [91]:
result

[(array([3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2])),
 (array([2, 4, 5, 6, 7, 8, 9]), array([0, 1, 3])),
 (array([2, 3, 5, 6, 7, 8, 9]), array([0, 1, 4])),
 (array([2, 3, 4, 6, 7, 8, 9]), array([0, 1, 5])),
 (array([2, 3, 4, 5, 7, 8, 9]), array([0, 1, 6])),
 (array([2, 3, 4, 5, 6, 8, 9]), array([0, 1, 7])),
 (array([2, 3, 4, 5, 6, 7, 9]), array([0, 1, 8])),
 (array([2, 3, 4, 5, 6, 7, 8]), array([0, 1, 9])),
 (array([1, 4, 5, 6, 7, 8, 9]), array([0, 2, 3])),
 (array([1, 3, 5, 6, 7, 8, 9]), array([0, 2, 4])),
 (array([1, 3, 4, 6, 7, 8, 9]), array([0, 2, 5])),
 (array([1, 3, 4, 5, 7, 8, 9]), array([0, 2, 6])),
 (array([1, 3, 4, 5, 6, 8, 9]), array([0, 2, 7])),
 (array([1, 3, 4, 5, 6, 7, 9]), array([0, 2, 8])),
 (array([1, 3, 4, 5, 6, 7, 8]), array([0, 2, 9])),
 (array([1, 2, 5, 6, 7, 8, 9]), array([0, 3, 4])),
 (array([1, 2, 4, 6, 7, 8, 9]), array([0, 3, 5])),
 (array([1, 2, 4, 5, 7, 8, 9]), array([0, 3, 6])),
 (array([1, 2, 4, 5, 6, 8, 9]), array([0, 3, 7])),
 (array([1, 2, 4, 5, 6, 7, 9]),

In [92]:
type(result)

list

In [93]:
len(result)

120